kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard

# 1. 永続ディスクを提供するprovisionerを指定
provisioner: kubernetes.io/gce-pd

# 2. Provisionerごとに指定できるパラメータは異なる
parameters:
  type: pd-standard
  replication-type: regional-pd

# 3. 動的にPersistent Volumesを作成するときの再要求時の挙動。デフォルトでは Delete。
#    Retainを設定すると、Persistent Volumeリソース削除時にデータを格納したボリュームを消さずに残す
reclaimPolicy: Retain

# 4. 動的にPersistent Volumesを作成するときに指定されるマウントオプション
mountOptions:
- debug

# 5. Persistent Volumeが使えるようになるタイミングを指定する。volumeBindingModeを指定
# すると、Persistent Volumeが使えるようになってから、バインドされる。Provisonerによっ
# てはWaitForFirstCosumerを指定できない
volumeBindingMode: WaitForFirstConsumer
