apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gce
spec:
  # 1. 永続ストレージのサイズを指定する
  capacity:
    storage: 5Gi
  # 2. 永続ストレージをFilesystemまたはrawのどちらかから指定する。
  # rawの場合、ブロックストレージとして提供される
  volumeMode: Filesystem
  # 3. アクセスモードをReadWriteOnce、ReadOnlyMany、ReadWriteManyの3つから選ぶ。
  # マウントするストレージの特性により、指定できるオプションに制限がある
  accessModes:
  - ReadWriteOnce
  # 3. 再び要求されたときの動作をRetain、Recycle、Deleteの3つから選ぶ。
  # RecycleはNFSとhostPathだけをサポートする。他のクラウドストレージなどはRetainで
  # 残すか、Deleteで削除するかのどちらかを指定する
  persistentVolumeReclaimPolicy: Retain
  # 4. PersistentVolumeClaimから要求されるときに名称として使う。
  # StorageClassのオブジェクト
  storageClassName: slow
  # 5. マウントする永続ストレージの種類を指定する。Google Compute Engineの永続ディスク
  # やNFSなど、さまざまなリソースを指定できる
  gcePersistentDisk:
    pdName: pd-reginal
    fsType: ext4
