apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kustdemo
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kustdemo
          servicePort: 80
