apiVersion: v1
kind: Pod
metadata:
  name: pod01
  labels:
    app: web01
spec:
  containers:
    - name: nginx01
      image: nginx
      ports:
        - containerPort: 80
          name: http-server
      volumeMounts:
        - mountPath: /var/www/html
          name: pvol
  volumes:
    - name: pvol
      persistentVolumeClaim:
        claimName: pvc001
