apiVersion: v1
kind: ServiceAccount
metadata:
  # 1. リソース名を指定
  name: test-serviceaccount
# 2. Tokenを自動でマウントするかどうかを指定。デフォルトはtrue
automountServiceAccountToken: true
# 3. (オプション)private repositoryにアクセスするためのsecretsを指定
imagePullSecrets:
- name: myregistrykey
