apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-cr
subjects:
- kind: Group
  name: k8s-user
- kind: User
  name: yamada
- kind: ServiceAccount
  name: defeult
