apiVersion: v1
kind: Pod
metadata:
  name: k8s.secret.pod
spec:
  containers:
  - name: k8ssecret
    image: nginx
    # volumeを/etc/userにリードオンリーでマウント
    volumeMounts:
    - name: user
      mountPath: "/etc/user"
      readOnly: true
  # volumesとしてsecretを設定
  volumes:
  - name: user
    secret:
      secretName: k8s.pocket.secret
