apiVersion: v1
kind: Pod
metadata:
  name: secret.env
spec:
  containers:
  - name: k8ssecretenv
    image: redis
    # 環境変数として、secretから設定
    env:
      # secret-sample.yaml(k8s.pocket.secret Secret)のusernameの値を
      # 環境変数PASSWORDに設定
      - name: USER
        valueFrom:
          secretKeyRef:
            name: k8s.pocket.secret
            key: username
      # secret-sample.yaml(k8s.pocket.secret Secret)のpasswordの値を
      # 環境変数PASSWORDに設定
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: k8s.pocket.secret
            key: password
  restartPolicy: Never
