apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      # 1. #2と値を一致させる
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        # 2. #1と値を一致させる
        name: fluentd-elasticsearch
    spec:
      # 3. ノードに設定されているtaintsに対応するtolerations設定
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-elasticsearch
        # 4. fluentd-elasticsearchイメージ
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
        # 5. マウントするボリュームの設定
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      # 6. ボリュームの設定
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
