apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello2
spec:
  schedule: "*/1 * * * * *" # ここが誤り
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello Kubernetes
          restartPolicy: OnFailure
